Rails.application.routes.draw do
  get 'photoshoot/index'
  get 'photoshoot/show'
  get 'photoshoot/new'
  get 'photoshoot/create'
  get 'photoshoot/edit'
  get 'photoshoot/update'
  get 'photoshoot/delete'
  get 'portfolio/index'
  get 'portfolio/show'
  get 'portfolio/new'
  get 'portfolio/create'
  get 'portfolio/edit'
  get 'portfolio/update'
  get 'portfolio/delete'
  get 'user/show'
  get 'user/new'
  get 'user/create'
  get 'user/edit'
  get 'user/update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
